[package]
name = "tsample"
version = "0.3.0"
authors = ["xudesheng <xudesheng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
log = "0.4"
env_logger = "0.7"
# pretty_env_logger = "0.2"
ctrlc = "3.1"
# crossbeam-channel = "*"
# crossbeam = "*"
# signal-hook = "*"
tokio = { version = "0.2", features = ["full"] }
influx-talk = {path="../rtwx/influx-talk"}
failure = "0.1.6"
toml = "0.5.6"
serde = "1.0.104"
chrono = "0.4"
reqwest = "0.10"
url = "2.1"
sys-info = "=0.7"
serde_json="1.0"
