title = "this is a demo."

[owner]
name = "Desheng Xu"
email = "dxu@ptc.com"
organization = "PTC Inc."

[testmachine]
testid = "twx85"
sampling_cycle_inseconds = 30
sampling_timeout_inseconds = 10

[testmachine.onetime_sampling]
os_type = true
os_release = true
cpu_num = true
cpu_speed = true
hostname = true

[testmachine.repeat_sampling]
cpu_load_one = true
cpu_load_five = true
cpu_load_fifteen = true
proc_total = true
mem_total = true
mem_free = true
mem_avail = true
mem_buffers = true
mem_cached = true
mem_used = true
swap_total = true
swap_free = true
disk_total = true
disk_free = true

[[thingworx_servers]]
alias = "platform_901"
host = "twx901.eastus2.cloudapp.azure.com"
port = 8080
protocol = "http"
application = "Thingworx"
app_key = "0203fcdc-9a92-45d5-8b10-4f37c36b80d3"

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "ValueStreamProcessingSubsystem"
enabled = true
options = ["totalWritesQueued", "totalWritesPerformed"]

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "DataTableProcessingSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "EventProcessingSubsystem"
enabled = true

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "PlatformSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "StreamProcessingSubsystem"
enabled = true

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "WSCommunicationsSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "WSExecutionProcessingSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "TunnelSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "AlertProcessingSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "FederationSubsystem"
enabled = false

[[thingworx_servers.metrics]]
split_desc_asprefix = true
name = "ClusteringSubsystem"
enabled = true

[result_export_to_db]
using_udp = false
server_name = "127.0.0.1"
port = 8087
database = "demo"
enabled = true

[result_export_to_file]
auto_create_folder = true
folder_name = "./export"
enabled = true
